# Generated by Django 4.0.5 on 2022-09-08 17:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts_followid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='postID',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='postID',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='post',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='userID',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='followID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number_of_followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number_of_following',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number_of_post',
        ),
        migrations.AlterField(
            model_name='follows',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follows',
            name='following',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 8, 17, 13, 35, 983433)),
        ),
    ]
