# Generated by Django 4.0.5 on 2022-09-14 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_postid_comments_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='is_liked',
        ),
        migrations.AlterField(
            model_name='posts',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 11, 43, 3, 686781)),
        ),
    ]
