# Generated by Django 4.0.5 on 2022-09-28 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_likes_is_liked_alter_posts_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backgroundColor',
            field=models.TextField(default='rgb(203, 68, 74)'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/images/profile.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 12, 50, 48, 175097)),
        ),
    ]
