# Generated by Django 4.0.5 on 2022-09-29 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_posts_datetime_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 15, 37, 30, 602299)),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile.png', null=True, upload_to=''),
        ),
    ]
