# Generated by Django 4.0.5 on 2022-10-04 01:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_user_bio_alter_comments_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 4, 1, 32, 59, 426756)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 4, 1, 32, 59, 426614)),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile.png', null=True, upload_to='media/'),
        ),
    ]
